Improvement/memory leak fixes
AkitaInteractive/Hachiko-Engine pull request #10
Opened 2022-02-17 20:14 UTC by miquelmiro3

2022-02-17 20:16 UTC, Erick9Thor approved these changes

2022-02-17 20:26 UTC, armandojaga requested changes

2022-02-17 20:26 UTC, armandojaga commented on Source/src/UI/WindowHierarchy.cpp
> +            if (selectedGameObject == game_object)
please add the braces to the if
if (condition)
{
}

2022-02-17 20:31 UTC, baransrc approved these changes
LGTM, thanks for the good work!!

2022-02-18 17:04 UTC, Bernatmago approved these changes

2022-02-18 21:34 UTC, baransrc approved these changes
Looks good to me!! Thanks for the work!

2022-02-18 21:38 UTC, armandojaga approved these changes
looks good

2022-02-18 22:14 UTC, Bernatmago approved these changes

2022-02-18 22:24 UTC, merged