Bind component animation to new resource model
AkitaInteractive/Hachiko-Engine pull request #100
Opened 2022-05-09 20:24 UTC by Erick9Thor

2022-05-10 22:37 UTC, Bernatmago approved these changes

2022-05-10 22:37 UTC, Bernatmago commented on Source/src/importers/ModelImporter.cpp
> +                     | aiProcess_GlobalScale | 0;
making a bitwise or with 0 makes literally no sense 👀

2022-05-11 00:55 UTC, baransrc requested changes

2022-05-11 00:55 UTC, baransrc commented on Source/src/importers/ModelImporter.cpp
> +                     | aiProcess_GlobalScale | 0;
```suggestion
                     | aiProcess_GlobalScale;
```

2022-05-11 00:55 UTC, baransrc commented on Source/src/importers/AnimationImporter.cpp
> +    i = 0;
```suggestion
```

2022-05-11 00:55 UTC, baransrc commented on Source/src/importers/AnimationImporter.cpp
> +    const auto file_buffer = new char[file_size];
```suggestion
    char* file_buffer = new char[file_size];
```

2022-05-11 00:56 UTC, baransrc approved these changes

2022-05-11 01:09 UTC, VBoschMatas commented
Engine crashes when I try to import a model that has no animations. I tried to delete the .meta and library but still does the same

2022-05-11 01:46 UTC, merged