Avoid player overlapping crystals and enemies.
AkitaInteractive/Hachiko-Engine pull request #196
Opened 2022-06-19 15:28 UTC by bernatgb

2022-06-19 18:38 UTC, miquelmiro3 commented on Source/src/components/ComponentAgent.cpp
> +        agent->params.radius = 2.0f;
We should try to hardcode number (magic numbers).

2022-06-19 18:46 UTC, miquelmiro3 commented
Hey tot bé. Només un parell de coses. Com el parasit de drop forma part del enemic el player el pot empuxar ja que es un agent igual que el drop. Suposo que es més un problema del que el drop forma part del enemic actualment quan s'hauria de instanciar però s'hauria de mirar potser abans de fer merge. També una pregunta per curiositat, no es podia fer que el player fos un obstacle més que un agent?

2022-06-19 18:48 UTC, miquelmiro3 commented
> 

I am used to talk to u in catalan, my bad. Traduction:

Just a couple of things. As the drop parasite is part of the enemy the player can push it as it is an agent just like the drop. I guess it's more of a problem of the drop being part of the enemy when it should be instantiated, but we should try to fix that  before merging. Also a question out of curiosity, couldn't the player be made more of an obstacle than an agent?

2022-06-19 19:08 UTC, baransrc requested changes
Thanks for the work!! We need some changes, after those are adressed, we are good to go!! 💯

2022-06-19 19:08 UTC, baransrc commented on Source/src/components/ComponentAgent.h
> +		bool player = false;
Let's rename this to is_player, the name "player" feels like a non-boolean object.

2022-06-19 19:08 UTC, baransrc commented on Source/src/components/ComponentAgent.cpp
> +    }
We shouldn't have this hard-coded by the name of the game object, engine should be as much as abstracted from the game it runs. Let's make a method of component agent that is: ComponentAgent::SetAsPlayer(bool is_player),  and we set the flag accordingly. If anything needs to be rebuilt based on is_player flag, we can set the appropriate variables based on the flag passed to SetAsPlayer.

2022-06-22 13:15 UTC, baransrc approved these changes
Everything works fine, I've added some changes and a little fix. Thanks for the great work 💯

2022-06-22 13:18 UTC, Erick9Thor approved these changes

2022-06-22 15:06 UTC, merged