Fix/state machine fixes and leaks
AkitaInteractive/Hachiko-Engine pull request #205
Opened 2022-06-22 12:32 UTC by Erick9Thor

This is a fix to avoid multiple leaks on the state machine generaton.

At the moment we don't know how to fix the library bug so we have opened a threat at https://github.com/thedmd/imgui-node-editor/issues/165

2022-06-22 15:47 UTC, Bernatmago approved these changes

2022-06-22 15:47 UTC, Bernatmago commented on Source/src/components/ComponentAnimation.cpp
> +                state_machine = static_cast<ResourceStateMachine*>(App->resources->GetResource(Resource::Type::STATE_MACHINE, uids[0]));
I recomend having a setter that always does this so u dont have to repeat the code

2022-06-24 10:59 UTC, alvarosoppelsa approved these changes

2022-06-26 17:35 UTC, Bernatmago requested changes
https://sonarcloud.io/project/issues?id=AkitaInteractive_Hachiko-Engine&pullRequest=205&resolved=false&types=BUG
We should deal with this

2022-06-26 19:15 UTC, Bernatmago commented on Source/vendors/imgui-node-editor-0.9/NodeEditor/Source/imgui_node_editor.cpp
> +    //drawList->ChannelsSetCurrent(c_UserChannel_Content);
Delete this if we are not using it, no point on leaving comented code

2022-06-28 08:33 UTC, closed without merging