Improve-Dash-feel-changing-how-it-is-interpolated-currently-linear
AkitaInteractive/Hachiko-Engine pull request #218
Opened 2022-06-28 18:47 UTC by EdwardRegasDuncan

Updated how dash is interpolated using Ease Out

2022-06-28 18:47 UTC, EdwardRegasDuncan commented
Task linked: [CU-2gbp7uh Improve Dash feel, changing how it is interpolated (currently linear)](https://app.clickup.com/t/2gbp7uh)

2022-06-28 19:57 UTC, Bernatmago approved these changes

2022-06-29 00:13 UTC, monikamnc requested changes

2022-06-29 00:13 UTC, monikamnc commented on Gameplay/entities/player/PlayerController.h
> +	SERIALIZE_FIELD(int, _dash_scaler);
```suggestion
	SERIALIZE_FIELD(unsigned int, _dash_scaler);
```
Hii! :3
I was testing the PR and when you add a negative number it brokes the position of the player game object and the camera look at too. I know it's not supposed to be negative in any case but I think we can change the _dash_scaler to unsigned int to be safe, or what do you think?
![image](https://user-images.githubusercontent.com/6739717/176324632-7eef93d5-a3da-4ccc-89d9-f15aa6415b82.png)

2022-06-29 00:25 UTC, monikamnc commented on Gameplay/entities/player/PlayerController.cpp
>  	// TODO: Instead of approaching to _dash_end linearly, dash must have some sort
```suggestion
	
```
Erase the TODO if it's finished ^-^

2022-06-29 07:56 UTC, monikamnc commented on Gameplay/entities/player/PlayerController.cpp
>  	// of an acceleration.
```suggestion
	
```

2022-06-29 07:57 UTC, monikamnc approved these changes
Thanks for your work ^-^

2022-06-29 08:14 UTC, merged