Beetle / Bug Enemy improved & invencibility time to player
AkitaInteractive/Hachiko-Engine pull request #236
Opened 2022-07-02 19:37 UTC by VBoschMatas

Beetle overall improvements.

- Idle has  a Patrol movement
- They now Spawn, being inmune to all damage while doing so
- They do "Player like" attacks, their attacks can be avoided by dashing or moving out of the area.

 The player has a short time of inmunity after being damaged
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Some extra changes regarding GameObject activation order. Children first, then parent.

2022-07-02 19:42 UTC, monikamnc commented
Credits to @VBoschMatas and @miquelmiro3 that helped my in my tiny commit :_) <3

2022-07-03 19:22 UTC, baransrc requested changes
Good f**👑 job guys!! After bunch of fixes we are good to merge 💯

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +	//	  break;
Let's delete this commented lines.

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +		//forward = forward.Normalized();
We can delete these if they won't be used in the follow-up pr for worm.

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +	//	transform->LookAtTarget(_player->GetTransform()->GetGlobalPosition());
Let's delete these.

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +	//
We can delete these if they are not needed.

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +		_idle_cooldown -= Time::DeltaTime();
```suggestion
		_idle_cooldown -= Time::DeltaTime();
		_idle_cooldown = _idle_cooldown < 0.0f ? 0.0f : _idle_cooldown;
```

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +	//_combat_stats->_max_hp = 2;
```suggestion
	_combat_stats = game_object->GetComponent<Stats>();
	_combat_stats->_attack_power = 1;
```

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +
```suggestion
```

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +			_idle_cooldown = 2.0f;
Maybe we can make this cooldown value settable through the editor?

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +	//_combat_stats->_max_hp = 2;
```suggestion
```

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/player/CombatManager.cpp
> +
```suggestion
```

2022-07-03 19:22 UTC, baransrc commented on Gameplay/entities/player/PlayerController.cpp
> +	if (_god_mode || _invulnerability_time_remaining > 0.0f)	return;
```suggestion
	if (_god_mode || _invulnerability_time_remaining > 0.0f)
	{
	    return;
	}
```

2022-07-03 20:12 UTC, alvarosoppelsa approved these changes

2022-07-03 20:13 UTC, miquelmiro3 approved these changes
All good! Just a couple of things, i think that the explosive crystal is not effecting enemies, the attack areas look good but a little weird maybe they are too fast, the idle patrol -> idle -> patrol behaviour is too fast (or maybe the end of the patrol is not detected properly).
Also are you going to make the player getting agro when shooting an enemy?

2022-07-03 20:51 UTC, VBoschMatas commented
> All good! Just a couple of things, i think that the explosive crystal is not effecting enemies, the attack areas look good but a little weird maybe they are too fast, the idle patrol -> idle -> patrol behaviour is too fast (or maybe the end of the patrol is not detected properly). Also are you going to make the player getting agro when shooting an enemy?

The explosive crystal thing I guess its something that's already in development because I haven't changed anything, but I was thinking about changing a bit the crystal behaviour to break other crystals (its a super small change, but to keep it separated), so I'll fix that there.
For the other things, sure gonan fix 'em asap

2022-07-03 22:16 UTC, baransrc approved these changes

2022-07-03 22:19 UTC, Bernatmago commented
![image](https://user-images.githubusercontent.com/28431584/177059044-d7f95138-8c79-486a-80c1-4793568757bc.png)
I didnt check the pr yet but have a look at this just in case

2022-07-04 01:11 UTC, merged