Window resources refactor
AkitaInteractive/Hachiko-Engine pull request #281
Opened 2022-07-30 09:29 UTC by alvarosoppelsa

This PR solves the issue of fps consumption by WindowResources. This is done by avoiding disk access on every update.
Also made a little change on the UI to split folders (header) and files (3 columns at the bottom).
I suck at UI so any suggestion or comment are more than welcome :)
Thanks!

2022-07-30 14:19 UTC, armandojaga requested changes

2022-07-30 15:13 UTC, alvarosoppelsa commented on Source/src/ui/WindowResource.cpp
> +    if (current_path != "./assets\\materials")
Did you try if this works? Just to be sure

2022-07-30 15:28 UTC, alvarosoppelsa commented on Source/src/ui/WindowResource.cpp
> +    if (current_path != "./assets\\materials")
It does :)

2022-07-30 15:50 UTC, alvarosoppelsa commented on Source/src/ui/WindowResource.cpp
> +    if (current_path != "./assets\\materials")
Done! I also change a few things if you can give me feedback would be nice

2022-07-30 17:20 UTC, armandojaga approved these changes
just an optional change to modernize ImGui

2022-07-30 17:20 UTC, armandojaga commented on Source/src/ui/WindowResource.cpp
> +    ImGui::Columns(1);
Columns is the old API way of organizing content, the new one is BeginTable, see Widgets::DragFloat for an example

2022-07-31 09:04 UTC, miquelmiro3 approved these changes
The UI is a bit clonky but i don't know how to improve it either xD, we can work on it after. Maybe i miss a refresh button since when you import a new model for example it doesn't appear in the folder inmidiately (maybe updating it after a file is dropped into the engine?) but it the same that going back and opening the folder again so well done.

2022-07-31 09:42 UTC, alvarosoppelsa commented
> The UI is a bit clonky but i don't know how to improve it either xD, we can work on it after. Maybe i miss a refresh button since when you import a new model for example it doesn't appear in the folder inmidiately (maybe updating it after a file is dropped into the engine?) but it the same that going back and opening the folder again so well done.

Thanks! What do you mean about clonky? When resizing? I'll work on the update button. Thanks for noticing

2022-07-31 12:36 UTC, alvarosoppelsa commented
@miquelmiro3 wanna test now? Added reloading when importing resources, do you think the update button is still needed?

2022-08-02 18:06 UTC, merged