Updated HUD for player
AkitaInteractive/Hachiko-Engine pull request #295
Opened 2022-08-29 18:42 UTC by Izenz

You should be able to find a new prefab called HUD_v2 containing everything. I also updated both levels and the player prefab so you should be able to see the changes reflected in both levels.

There are no functional changes to the HUD besides it changing display depending on the weapon the player is holding. Feel free to drop a comment or DM me on Discord if you see something weird.

2022-08-29 21:16 UTC, Bernatmago requested changes
It works perfectly amazing job! I think level is saved in some state that is not the initial one, i recommend u copying it again from dev and setting up the hud there

2022-08-30 17:29 UTC, miquelmiro3 requested changes
I agree with the offset of the animations (it could be a parameter in image that randomizes at the start the starting time), also in level 2 you begin with 3 of health is that some way related to this changes??

2022-08-31 16:18 UTC, miquelmiro3 approved these changes

2022-08-31 19:12 UTC, Bernatmago approved these changes

2022-08-31 19:31 UTC, merged