Reorganize enemies code
AkitaInteractive/Hachiko-Engine pull request #297
Opened 2022-08-29 21:06 UTC by Bernatmago

2022-08-30 01:00 UTC, monikamnc approved these changes
Tested just in case something stops working but everything its perfect.

Thank you for the work!

2022-08-30 17:47 UTC, miquelmiro3 requested changes
It looks like everything is good except one thing, the enemies flip around sometimes could it be for some of these changes??

https://user-images.githubusercontent.com/52320536/187507466-4116a6be-a5f3-4620-89e9-676d620012af.mp4

2022-08-31 16:28 UTC, monikamnc commented
> It looks like everything is good except one thing, the enemies flip around sometimes could it be for some of these changes??
> Hachiko.2022-08-30.19-43-06.mp4

We have this in the PR #283 so it's not because of this code but we should take a look.

2022-08-31 17:01 UTC, miquelmiro3 approved these changes

2022-08-31 19:31 UTC, merged