Fix/heal vfx requested changes
AkitaInteractive/Hachiko-Engine pull request #341
Opened 2022-09-14 12:11 UTC by EdwardRegasDuncan

2022-09-14 12:32 UTC, monikamnc requested changes
I think you forgot to push the vfx changes because they remain the same as we had before.

2022-09-15 19:30 UTC, monikamnc commented
I have this error testing the PR
![image](https://user-images.githubusercontent.com/6739717/190492633-16e65bf8-bd43-4ffe-82ef-15feb31851fe.png)

It appears when you hit an enemy

2022-09-16 23:59 UTC, baransrc approved these changes
Thanks for the work, I've fixed the issue @monikamnc said, and it turned out to be the absence of TimeManager script attached to the CombatManager game object on Level.scene. Also, the new vfx looks better relative to the old version ❤️

2022-09-17 00:01 UTC, Bernatmago approved these changes

2022-09-17 00:02 UTC, merged