Boss spawn enemies
AkitaInteractive/Hachiko-Engine pull request #343
Opened 2022-09-17 18:27 UTC by miquelmiro3

For the task: If combat form: Enemies from lvl 1 & 2 spawns to ensure change weapon to the player triggered by time (for example each 10 seconds to test?)

For testing play the boss scene, after 5 seconds in combat it spawns an enemy (max 2). Let me know if this is what we wanted.

2022-09-18 18:51 UTC, monikamnc approved these changes
I think for now it's ok ^-^
We can improve it when we have all phases of the boss working.
Great work!

2022-09-22 17:41 UTC, baransrc requested changes
Good work!! There are couple of suggestions that you can address, after that I think we are good to merge!

2022-09-22 17:41 UTC, baransrc commented on Gameplay/entities/enemies/BossController.cpp
> +	}
```suggestion
	if (enemy_timer < time_between_enemies)
	{
            return;
        }

        for (EnemyController* enemy_controller : enemies) 
        {
            GameObject* __restrict enemy = enemy_controller->GetGameObject();

            if (enemy->IsActive())
            {
                continue;
            }

            enemy->SetActive(true);
            ComponentAgent* __restrict agent = enemy->GetComponent<ComponentAgent>();
        
            if (agent)
            {
                agent->AddToCrowd();
            }
            
            break;
        }

        enemy_timer = 0;
```

2022-09-22 17:41 UTC, baransrc commented on Gameplay/entities/enemies/BossController.cpp
> +}
```suggestion
void Hachiko::Scripting::BossController::ResetEnemies()
{
	for (EnemyController* enemy_controller : enemies)
	{
        GameObject* __restrict enemy = enemy_controller->GetGameObject();
		ComponentAgent* __restrict agent = enemies[i]->GetGameObject()->GetComponent<ComponentAgent>();
		
        if (agent)
		{
			agent->RemoveFromCrowd();
		}
		
        if (enemy_controller)
		{
            // Maybe pack these methods into a method of EnemyController for
            // ease of extensibility.
			enemy_controller->SetIsFromBoss(true);
			enemy_controller->ResetEnemy();
			enemy_controller->ResetEnemyPosition();
		}
		
        enemy->SetActive(false);
	}
}
```

2022-09-23 09:31 UTC, Erick9Thor approved these changes

2022-09-26 15:39 UTC, baransrc approved these changes

2022-09-26 16:15 UTC, merged