Fix/fps problem
AkitaInteractive/Hachiko-Engine pull request #344
Opened 2022-09-18 16:44 UTC by miquelmiro3

I think that with this pr the problem of the player getting a fall hit at the begining of the level is also solved. There is no much to test everything should feel the same. The main problem was that the correction applied to the player position was always fixed so if fps were low the delta time would increase and that would go through the threshold we had and the player would starts to fall if it walked to the edge or even sometimes some jump became imposible.

Also added in this PR:
- When boss is hitted its emissive is changed
- Beetles dont attack u more if player is dead
- Reorder the reloading of the skybox (that modifies the loading screen to half it size, so now the time when that happens are less)

For now I also made some changes to avoid crashes:
- Commented subscription of Particles to the SelectObject effect
- Try catch added to the Refresh label of component text

2022-09-18 18:42 UTC, monikamnc approved these changes
Perfect working!

Sonnar complaining for some conversions and commented code you can check it but it's ok.

2022-09-20 12:45 UTC, armandojaga requested changes

2022-09-20 16:23 UTC, miquelmiro3 commented on Source/src/components/ComponentParticleSystem.cpp
> +    /* std::function selection_changed = [&](Event& evt) {
It is being called when we load a new scene selecting a nullptr go and for some reason a destroied particlesystem or a not intialized one caught it and was crashing.

2022-09-22 17:43 UTC, baransrc approved these changes

2022-09-22 21:31 UTC, armandojaga approved these changes

2022-09-23 20:27 UTC, merged