Fix/debug window
AkitaInteractive/Hachiko-Engine pull request #353
Opened 2022-09-26 16:48 UTC by ermario

I added back the debug window for Level 1 and Level 2, I removed some useless functionalities and added new ones (change weapon) that could be useful for testing.

PLEASE, check the prefabs and models to see that I didnt fucked up anything. I had lots of problems with libraries and assets so I did a mess probably. Glasias!

2022-09-26 23:51 UTC, Izenz requested changes
Hey!

When I instantiate the Debug Window prefab onto a scene its script is missing all the references except Tp Pos 1/2/3.
I added the references and tested out a bit tho, here's my opinion.

- Spawn enemy button crashes the game.
- Would be nice to display Atk power and Mov speed values to edit them propperly.
- Atk. Power and Mov. speed can take negative values resulting in weird unwanted behavior, would be wise to clamp after editing.
- Tp Pos values teleport outside the map, may want to fix their values.

Cheers!

2022-09-27 17:24 UTC, baransrc requested changes
Thanks for the good contribution. Some small changes, afterwards, we are good to go given that the issues brought up by @Izenz are addressed.

2022-09-27 17:24 UTC, baransrc commented on Gameplay/entities/player/PlayerController.cpp
> +	if (0 < ammo && ammo <= MAX_AMMO)
```suggestion
	if (ammo <= MAX_AMMO) 
```
No needs to check for smaller than zero as ammo is unsigned.

2022-09-27 17:24 UTC, baransrc commented on Gameplay/entities/player/PlayerController.cpp
> +	}
Maybe it's a better idea to add an assert statement here instead of a HE_LOG as no one checks there :eyes:

2022-09-27 17:29 UTC, ermario commented
> Hey!
> 
> When I instantiate the Debug Window prefab onto a scene its script is missing all the references except Tp Pos 1/2/3. I added the references and tested out a bit tho, here's my opinion.
> 
> * Spawn enemy button crashes the game.
> * Would be nice to display Atk power and Mov speed values to edit them propperly.
> * Atk. Power and Mov. speed can take negative values resulting in weird unwanted behavior, would be wise to clamp after editing.
> * Tp Pos values teleport outside the map, may want to fix their values.
> 
> Cheers!

Regarding this, spawn enemy right now can not be fixed because whenever you create a prefab of the enemy, the enemy controller does not initialize the values from function OnStart(), (since game is already started) because of this it just explodes.
Regarding the other issues I did some fixes and changed some more stuff. Thanks for your feedback

2022-09-27 17:33 UTC, ermario commented
Also found that when using the teleport buttons the character performs the attack (on clicking the button) this will cause the player to not teleport because is on attack animation... Instead if you click on the button while you hold right button (charge shot) , you can teleport without any problem 😂

2022-09-27 22:02 UTC, baransrc approved these changes

2022-09-27 22:29 UTC, Izenz approved these changes

2022-09-27 22:50 UTC, merged