Update sand and tiles hd textures.
AkitaInteractive/Hachiko-Engine pull request #356
Opened 2022-09-27 06:01 UTC by bernatgb

Updated sand and tiles hd textures.

2022-09-27 10:53 UTC, monikamnc approved these changes
noice 
Albah euq napel

2022-09-27 11:45 UTC, armandojaga approved these changes

2022-09-27 13:47 UTC, Bernatmago requested changes
Shouldnt we modify the level so it uses the new textures? Im assuming the ones that are modified are automatically replaced since its the seme id but it seems that there are many new ones

2022-10-06 18:16 UTC, Bernatmago approved these changes

2022-10-06 18:52 UTC, merged