applied fade in effect on spawn
AkitaInteractive/Hachiko-Engine pull request #363
Opened 2022-09-28 13:18 UTC by EdwardRegasDuncan

2022-09-29 22:45 UTC, baransrc requested changes
Thanks for the work!! I requested small changes and a clarification, afterwards we are good to go.

2022-09-29 22:45 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +			//_enemy_body->ChangeEmissiveColor(float4(0.3f, 0.5f, 1.0f, 1.0f), _spawning_time, true);
Let's delete this comment.

2022-09-29 22:45 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.h
> +            const float spawn_rate = 1 / math::Sqrt(_spawning_time);
Why division by Sqrt?

2022-09-29 22:45 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +		}
```suggestion
		spawn_progress += spawn_rate * Time::DeltaTime();
		spawn_progress = spawn_progress > 1.0f ? 1.0f : spawn_progress;
		
		_enemy_body->ChangeTintColor(float4(1.0f, 1.0f, 1.0f, spawn_progress), true);
```

2022-09-29 22:45 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.cpp
> +			//_enemy_body->ChangeEmissiveColor(float4(0.3f, 0.5f, 1.0f, 1.0f), _spawning_time, true);
```suggestion
```

2022-09-30 16:50 UTC, bernatgb reviewed
Good job, but it feel a bit weird see the enemies appear, disappear, and then spawning with the fade effect.

Apart from that, sometimes the enemies remain invisible:
![bugbug](https://user-images.githubusercontent.com/33035442/193316964-2eb9f346-9cb6-4653-a4a4-2d95bdc195ae.png)
_I'm in god mode here, but it still happens even if I turn it off._

2022-10-01 14:09 UTC, baransrc requested changes

2022-10-01 14:09 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.h
> +            SERIALIZE_FIELD(float, _current_spawning_time);
Let's remove this if we are not using it.

2022-10-01 14:09 UTC, baransrc commented on Gameplay/entities/enemies/EnemyController.h
> +            bool _has_spawned = false;
Let's remove this if we are not using.

2022-10-06 21:28 UTC, baransrc approved these changes

2022-10-07 18:10 UTC, Bernatmago approved these changes
Works like a charm thanks!
A PR description saying what change is expected to be noticeable and how to test it, even if very brief, would be greatly appreciated in the future!

2022-10-07 18:10 UTC, merged