Update Player's vfx on Boss scene
AkitaInteractive/Hachiko-Engine pull request #385
Opened 2022-10-09 14:42 UTC by alvarosoppelsa

On Boss scene were updated player's vfx for health, chargind and shooting. For all the levels some particles were added for dashing

2022-10-09 20:29 UTC, monikamnc requested changes
Stop until we have new scenes updated, sorry >.

2022-10-10 11:52 UTC, bernatgb approved these changes
Good job! However I would exaggerate more the dash particles.

2022-10-10 12:31 UTC, alvarosoppelsa commented
> Good job! However I would exaggerate more the dash particles.

Ok! Like more particles, particles stay longer time, bigger particles?

2022-10-10 17:56 UTC, monikamnc approved these changes
Unblock

2022-10-10 18:25 UTC, alvarosoppelsa commented
> Unblock

Sadly it isn't

2022-10-10 21:44 UTC, Izenz approved these changes
Looks good!

2022-10-11 08:49 UTC, Izenz commented on Gameplay/CutsceneManager.h
> +#include <scripting\Script.h>
```suggestion
#include <scripting/Script.h>
```
You should change this btw.

2022-10-11 09:04 UTC, merged