Upgrading logging system
AkitaInteractive/Hachiko-Engine pull request #71
Opened 2022-04-22 23:35 UTC by armandojaga

- allow different logging types (console, imgui, files...)
- allow different logging levels (debug, info, error)

2022-04-23 08:46 UTC, Bernatmago approved these changes

2022-04-23 09:01 UTC, alvarosoppelsa approved these changes

2022-04-23 09:39 UTC, monikamnc approved these changes
Thank you for the upgrading!

2022-04-23 10:54 UTC, monikamnc requested changes
Hello again,
Now I realize that SonnarCloud couldn't run the check and it seems that has errors on the scripting system that doesn't find the loggings system of the engine.
Can you check it? @armandojaga @baransrc

2022-04-24 10:24 UTC, monikamnc approved these changes
Nice ;)

2022-04-24 16:19 UTC, merged