Meta files standarization
AkitaInteractive/Hachiko-Engine pull request #76
Opened 2022-04-26 18:51 UTC by miquelmiro3

2022-04-27 16:39 UTC, VBoschMatas commented
Everything looks fine, but if I double click on any .meta file it will try to load a model from it. But for now we can just literally avoid doing that directly, and after that at some point check the meta type and if we have an object selected and we double click a material change its meterial to the selected and for niche or confusing things just do nothing when double clicking.

2022-04-27 16:39 UTC, VBoschMatas approved these changes

2022-04-27 16:51 UTC, alvarosoppelsa commented
I'll fix the bug right now and I'll try to add the material change for the selected object. Thank you for testing!

2022-04-27 16:55 UTC, Bernatmago commented on Source/src/modules/ModuleResources.h
>          std::map<UID, ResourceMesh*> meshes;
we can remove these specific maps

2022-04-27 17:14 UTC, Bernatmago requested changes
I talked with Miquel and we should not regenerate meta files because timestamp changes and git wants to track the changes (or remove timestamp from them otherwise)

2022-04-27 18:35 UTC, alvarosoppelsa commented
@VBoschMatas I've added material selection by double clicking in WindowResources. Could you give it a look? Let me know what you think. Thanks! :)

2022-04-27 18:58 UTC, VBoschMatas commented
> @VBoschMatas I've added material selection by double clicking in WindowResources. Could you give it a look? Let me know what you think. Thanks! :)

Looks nice and intuitive, I've seen that double clicking on other things does not crash the engine. Good job!

2022-04-27 20:43 UTC, armandojaga requested changes

2022-04-28 08:49 UTC, alvarosoppelsa commented on Source/src/importers/Importer.h
> +        virtual void ImportWithMeta(const char* path, YAML::Node& meta) = 0;
It's a really good point. We've splitted functionality when we are importing a new file and when already have created the meta file. We've talk to do a code improvement, is it ok for you if we add a TODO comment for reviewing this after merge?

2022-04-28 09:16 UTC, alvarosoppelsa commented on Source/src/importers/ModelImporter.h
> +        //Resource* CherryImport(int mesh_index, const UID uid, const char* model_path); // TODO: To remove
Done

2022-04-28 09:17 UTC, alvarosoppelsa commented on Source/src/importers/ModelImporter.cpp
> +//Hachiko::Resource* Hachiko::ModelImporter::CherryImport(int mesh_index, const UID uid, const char* model_path)
Done

2022-04-28 16:42 UTC, Bernatmago approved these changes

2022-04-28 18:43 UTC, miquelmiro3 commented on Source/src/importers/AnimationImporter.cpp
> +void Hachiko::AnimationImporter::ImportWithMeta(const char* path, YAML::Node& meta)
The main difference is that in the first one the import puts data in the meta and uses only the id that contains. In the ImportWithMeta it uses all the data inside the meta to make the import, and writes only the new data of the assets. For example, on a model import the first one would write on the meta that the mesh1 has the id 1, and in the second one the importwithmeta would read that the mesh1 has the id 1 and would import it acording that data.
Hope this makes sense.

2022-04-30 18:30 UTC, baransrc reviewed
Good work, there are some things need to be clarified. Also Github didn't let me review everything, I think there is an issue with it right now. I could only submit my comments from 2 days ago + .gitignore.

2022-04-30 18:30 UTC, baransrc commented on .gitignore
> -
Why are we deleting these?

2022-04-30 18:30 UTC, baransrc commented on .gitignore
> -
Same here

2022-04-30 23:31 UTC, Bernatmago commented on Source/src/importers/Importer.h
> +        virtual void ImportWithMeta(const char* path, YAML::Node& meta) = 0;
Import with meta should be load from meta and there will be no confusion <3

2022-04-30 23:32 UTC, Bernatmago commented on Source/src/importers/Importer.h
> +        virtual void ImportWithMeta(const char* path, YAML::Node& meta) = 0;
You can also change import to Import and fill/populate meta

2022-04-30 23:38 UTC, Bernatmago commented on Source/src/core/serialization/Definitions.h
>  #define RENDER_NODE "render"
Yep could be better

2022-04-30 23:44 UTC, baransrc commented on Source/src/core/preferences/src/ResourcesPreferences.h
> +            {Resource::Type::FONT, "library/fonts/"},
```suggestion
            {Resource::Type::FONT, "assets/fonts/"},
```

2022-04-30 23:46 UTC, baransrc approved these changes

2022-04-30 23:52 UTC, merged