Feature/deform mesh using nodes skining
AkitaInteractive/Hachiko-Engine pull request #86
Opened 2022-05-01 21:40 UTC by Erick9Thor

2022-05-01 21:41 UTC, Erick9Thor commented on Game/assets/shaders/vertex.glsl
> +};*/
I will change this when we have batching and SSBO.

2022-05-01 21:50 UTC, Erick9Thor commented on Source/src/components/ComponentMesh.cpp
> +            /* const GameObject* bone_node = node_cache[i];
This is another improve that apears on the diapo called Cache bones. @baransrc if you want i can dedicate time to implemnt i think it's easy and improve the performance.

2022-05-01 23:47 UTC, Bernatmago approved these changes

2022-05-02 00:05 UTC, baransrc requested changes
Thanks for the awesome job as always, I requested a small change, after that we are good to go!!🔥

2022-05-02 00:05 UTC, baransrc commented on Source/src/importers/MeshImporter.cpp
> +    }
I believe you follow what we had previously here. This is not a comment for you, but rather a note to the future us, we can delete all this `if else` hell, and just assign `nullptr` or `0` to everything at start and just leave the `if`s.

2022-05-02 12:46 UTC, monikamnc approved these changes
Tested and working on my machine, 
I had to delete Library because I was having super strange errors but then it works perfectly.
I agree with @baransrc comments.

2022-05-02 14:39 UTC, armandojaga requested changes

2022-05-02 14:39 UTC, armandojaga commented on Source/src/core/GameObject.cpp
> +
I agree that the name can be misleading as to what the intent is, I'd make some other changes as well, call the method `FindDescendant` and return `nullptr ` if it doesn't find anything

2022-05-03 00:05 UTC, baransrc approved these changes

2022-05-03 09:37 UTC, alvarosoppelsa commented on Source/src/core/GameObject.cpp
> +}
Is there any reason for iterating two times over the children? if not, the content could be in just one for loop, I think is better for performance and for reading the code

2022-05-03 09:43 UTC, armandojaga approved these changes

2022-05-03 09:59 UTC, merged