Add Wwise Project with Background Music
AkitaInteractive/Hachiko-Engine pull request #95
Opened 2022-05-05 18:49 UTC by monikamnc

🎵 With this PR you will see the new folder for the Wwise project in the root folder. 
🎵 You will find on the Wwise Project that there are some audio files from plugins at this point I am testing with them so I will leave there, when I approach to the final version for sure I will erase it.
🎵 Also, I searched for the suggested by the community files that I should ignore and also I added them to the gitignore file.

🎵 If you want to listen to the Background Music you should uncomment the line 144 on Module Audio. 
🎵 I leave it commented to avoid the programmers hate me and go crazy listening to the music each time are going to compile and test the Engine.

🎵 Thank you for your time ^-^

2022-05-06 01:08 UTC, baransrc requested changes
Thanks for the great work, I've also tested uncommenting the line that fires up the background music and it's great as well!! Just some really small changes are needed to maintain a good quality on what's being merged into our default branch 💯

2022-05-06 01:12 UTC, baransrc commented on Source/src/modules/ModuleAudio.cpp
> +#include "..\..\WwiseAkitaInteractive\GeneratedSoundBanks\Wwise_IDs.h" // IDs generated by Wwise
Btw, the illegal characters thing sonarr says is true, `\` without trailing escape like `\\` may make the next character(s) be interpreted as other special characters such as `\n`, and probably by our luck, our compiler tolerates that.

2022-05-06 08:08 UTC, monikamnc commented on Source/src/modules/ModuleAudio.cpp
> +#define BANKNAME_TEST L"TestBGMusic.bnk"
Thank you for the review and sorry, I followed the tutorials and didn't realize that.
I changed it, take a look if its the way you had in mind or not.
(●ᴥ●)

2022-05-06 08:09 UTC, monikamnc commented on Source/src/modules/ModuleAudio.cpp
> +#include "..\..\WwiseAkitaInteractive\GeneratedSoundBanks\Wwise_IDs.h" // IDs generated by Wwise
Done, thank you 😺

2022-05-06 11:36 UTC, baransrc approved these changes

2022-05-08 15:30 UTC, VBoschMatas approved these changes

2022-05-08 21:08 UTC, merged